Thread #x was created
   ...
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: main (in /home/alessandro/Projects/advhg/helgrind/tests/adv02_heap)

Thread #x was created
   ...
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: main (in /home/alessandro/Projects/advhg/helgrind/tests/adv02_heap)

Possible data race during read of size 4 at 0x........ by thread #x
   at 0x........: f2 (in /home/alessandro/Projects/advhg/helgrind/tests/adv02_heap)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...
 This conflicts with a previous write of size 4 by thread #x
   at 0x........: f1 (in /home/alessandro/Projects/advhg/helgrind/tests/adv02_heap)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...

Possible data race during read of size 4 at 0x........ by thread #x
   at 0x........: f2 (in /home/alessandro/Projects/advhg/helgrind/tests/adv02_heap)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...
 Address 0x........ is 0 bytes inside a block of size 4 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f1 (in /home/alessandro/Projects/advhg/helgrind/tests/adv02_heap)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...

